wallpaper_directory = "/home/linde/.local/share/wallpapers"
wallpaper_whitelist = [
    "wallhaven-yq7wqg.png",
    "wallhaven-gwzvwd.png",
    "wallhaven-vpx7k3.jpg",
    "wallhaven-gwjpp3.jpg",
    "wallhaven-yqjm9x.jpg",
    "2d-digital-art-landscape-forest-wallpaper-598008edb1cadd3bc627c87fd051d68d.jpg",
    "koi-fish-koi-fish-illustration-wallpaper-72a1a290bd96bebb1ac872b5b0683972_upscayl_2x_upscayl-standard-4x.png",
    "simple-background-fish-flowers-digital-art-minimalism-grey-fish-with-pink-flower-illustration-wallpaper-e9a0b8ad017a2d9bc6d718cfb001d65d.jpg",
    "anime-manga-minimalism-simple-background-wallpaper-99f0f80d31ea7d4be627b8ff1081962d.jpg",
    "berserk-kentaro-miura-monochrome-sky-wallpaper-8ee7ac70eac072bff62f20b79f84f0cf.jpg",
    "1750351959203471.png"
]
