[general]
import = ["/home/olinde/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 14

[font.normal]
family = "Hack"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
command = { program = "nautilus", args = ["."] }
key = "F"
mods = "Control|Shift"

[window]
opacity = 0.9

